### ISSUE TITLE
No localization

### ISSUE THREAD

**Issue by Akhun-Delar** [pretix/pretix-sepadebit#32]
Currently, it seems like languages other than English don't work. Admin interface and user frontend (shop) are always in English

**Comment by raphaelm** [comment]
You most likely did not execute all steps of the plugin installation as per the pretix docs. It works for me.

**Comment by Akhun-Delar** [comment]
For context, I am running on Docker. This is what I did. Anything I forgot? Because that's exactly what the docs tell me to do.
```
FROM pretix/standalone:stable
USER root
RUN pip3 install pretix-sepadebit
USER pretixuser
RUN cd /pretix/src && make production
```

Also with the following, nothing changes: 
```
[languages]
enabled=de
```

**Comment by Akhun-Delar** [comment]
Interestingly, some parts are loaded in German, but the most important parts are not: [Screenshot](https://prnt.sc/5Pnu0Z9fvPPI)

**Comment by Akhun-Delar** [comment]
Problem seems to be more than just this plugin, closing and opening discussion on the main project
