### ISSUE TITLE
BIC/IBAN combination results in hard fail even though it's correct

### ISSUE THREAD

**Issue by Akhun-Delar** [pretix/pretix-sepadebit#34]
There seems to be some list of BICs running in the background, which then blocks buying tickets when it doesn't match with the IBAN. I have a customer that complained that his BIC doesn't work. IBAN-Rechner.de shows, that the BIC he provided is definitely correct with the BIC.

I can't provide sample data due to GDPR, but maybe there could be a checkbox to confirm the data (in case only the combination fails) or some other solution, so it's not hardfailing and not keeping customers from buying limited tickets.

**Comment by raphaelm** [comment]
Can you share which BIC this is without revealing personal data?

**Comment by Akhun-Delar** [comment]
COBADEFFXXX

This issue seems to be known for nearly ten years. Commerzbank seems to tell their customers to use their "central" BIC (COBADEFF), while officially, the IBANs are to be used with the BIC of their local bank branch (for example COBADEHH). See: https://jverein-forum.de/viewtopic.php?t=1998
