### ISSUE TITLE
sepadd module not found

### ISSUE THREAD

**Issue by thegcat** [pretix/pretix-sepadebit#9]
On update to Pretix 2.5.0 today I encountered the following bug:

```
  File "/var/pretix/venv/lib/python3.6/site-packages/pretix_sepadebit/views.py", line 17, in <module>
    from sepadd import SepaDD
ModuleNotFoundError: No module named 'sepadd'
```

Changing the import in the `views.py` file to `from sepaxml import SepaDD` fixes the problem, though I imagine this would also need to be reflected in the `setup.py` at least too.

**Comment by raphaelm** [comment]
Yes, it should be ``from sepaxml``, but ``sepadd`` should have a compat wrapper to still support it. Anyways, I'm releasing 1.5.1 right now to address this.

**Comment by thegcat** [comment]
This seems to fix the problem, thanks!

I had seen that there were supposed to be a compat layer, but the `site-packages` from our venv, everything installed through pip, only has a `sepadd-2.0.0.dist-info` and no code for it, and the `sepaxml` code in the `site-packages` doesn't seem to come with a compat layer for `sepadd` that I could see.
